config/routes.rb
Rails.application.routes.draw do
  get '/items/me', to: 'items#me'
  resources :items do
    resources :books
    resources :reviews
  end
  devise_for :users
  resources :users do
    resources :reviews
  end
  root to: 'items#index'
end

app/models/item.rb
class Item < ApplicationRecord
  include ImageUploader::Attachment.new(:image)
  include Filterable
  has_many :reviews, as: :reviewcontainer, dependent: :destroy
  belongs_to :user
  belongs_to :category
  has_many :books, dependent: :destroy


=begin
  extend ItemSpliter
  split(name)
=end

  before_save :initial_rate

  def initial_rate
    self.rating ||= 0
  end

  def self.average_rating
    average(:rating)
  end

  validates :price, presence: true, format: {with: /\A\d+(?:\.\d{0,2})?\z/},
            numericality: {greater_than: 0, less_than: 1_000_000}

  scope :by_city, ->(city_ids) {
    joins(:user)
        .where(users: {city_id: city_ids})
  }
  scope :by_category, ->(category_ids) {
    joins(:category)
        .where(categories: {id: category_ids})
  }
  scope :by_title, ->(str) {where(arel_table[:name].matches("%#{str}%"))}

  def self.book_interval(term_start, term_end)
    item_table = Item.arel_table
    book_table = Book.arel_table
    bedbooks = Book.where(book_table[:start_booking].lt(term_end)
                              .and(book_table[:end_booking].gt(term_start)))
    Item.where.not(item_table[:id].in(bedbooks.map(&:item_id)))
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :authenticate_user!
  skip_before_action :authenticate_user!, on: [:index]

  def new
    @item = Item.new
    @categories = Category.all
  end

  def create
    p '1'*100
    p item_params[:image]
    p '1'*100

    @item = Item.new(item_params)
    @item.user = current_user
    if @item.save
      redirect_to items_me_path
    else
      @categories = Category.all
      render 'new'
    end
  end

  def update
    # add errors
    @item = Item.find(params[:id])
    @item.update(item_params)
    @items = Item.where(user: current_user)
    redirect_to items_me_path
  end

  def edit
    @item = Item.find(params[:id])
    @categories = Category.all
  end

  def destroy
    @item = Item.find(params[:id])
    @item.destroy
    @items = Item.where(user: current_user)
    redirect_to items_me_path
  end

  def me
    @items = Item.where(user: current_user)
  end

  def index
    @cities = City.all
    @categories = Category.all
    if params[:filter]
      params[:by_title].strip!
      @items = Item.book_interval(container_time[:start_booking], container_time[:end_booking])
                   .filter(params.slice(:by_title, :by_city, :by_category))
                   .where.not(user: current_user)
=begin
      @items = Item.includes(:books)
                   .by_city(params[:filter][:city_id])
                   .by_title(params[:filter][:title])
                   .book_interval(container_time[:start_booking], container_time[:end_booking])
                   .by_category(params[:filter][:category_id])
                   .where.not(user: current_user)
=end
    else
      @items = Item.where.not(user: current_user)
    end
  end

  def show
    @item = Item.find(params[:id])
  end

  private

  def item_params
    params.require(:item).permit(:description, :category_id, :price, :image)
  end


  def container_time
    start_booking = DateTime.new(params[:filter]['start_booking(1i)'].to_i,
                                 params[:filter]['start_booking(2i)'].to_i,
                                 params[:filter]['start_booking(3i)'].to_i,
                                 params[:filter]['start_booking(4i)'].to_i,
                                 params[:filter]['start_booking(5i)'].to_i,
                                 0)
    end_booking = DateTime.new(params[:filter]['end_booking(1i)'].to_i,
                               params[:filter]['end_booking(2i)'].to_i,
                               params[:filter]['end_booking(3i)'].to_i,
                               params[:filter]['end_booking(4i)'].to_i,
                               params[:filter]['end_booking(5i)'].to_i,
                               0)
    { start_booking: start_booking, end_booking: end_booking }
  end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/destroy.html.erb
<h1>Items#destroy</h1>
<p>Find me in app/views/items/destroy.html.erb</p>

app/views/items/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class=' col-md-4'>
    </div>
    <div class=' col-md-4 align-self-center'>
      <% if @item.errors.any? %>
        <div class='error_explanation'>
          <h4><%= pluralize(@item.errors.count, 'error') %></h4>
          <ul>
            <% @item.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_for @item do |f| %>
        <div class='form-group'>
          <label for='usr'>Description:</label>
          <%= f.text_area :description %><br>
          <label for='usr'>Price:</label>
          <%= f.text_field :price %><br>
          <div class='field'>
            <%= f.label :Select_item_Category %>
            <%= f.collection_select(:category_id, @categories, :id, :title, prompt: true) %>
            <%= f.label :image %><br>
            <%= f.file_field :image %>
          </div>
        </div>
        <%= f.submit 'Save' %>
      <% end %>
    </div>
    <div class='col-md-4'>
    </div>
  </div>
</div>

app/views/items/index.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-4'></div>
    <div class='col-md-4'>
      <!-- Trigger the modal with a button -->
      <button type='button' class='btn btn-info btn-lg' data-toggle='modal' data-target='#myModal'>Filter(not work)
      </button>
    </div>
    <div class='col-md-4'></div>
  </div>
  <!-- Modal -->
  <div id='myModal' class='modal fade' role='dialog'>
    <div class='modal-dialog'>

      <!-- Modal content-->
      <div class='modal-content'>
        <div class='modal-header'>
          <button type='button' class='close' data-dismiss='modal'>&times;</button>
          <h4 class='modal-title'>Filter for Items</h4>
        </div>


        <div class='modal-body'>
          <%= form_tag root_path, method: :get do %>
            <!--        <%= collection_select(:filter, :city_id, City.all,
                                              :id, :title, {prompt: 'Please select Cities'}, {multiple: true}) %>
            <%= collection_select(:filter, :category_id, Category.all,
                                  :id, :title, {prompt: 'Please select Categories'}, {:multiple => true}) %><br>
              <label>City:</label>
            <%#= collection_check_boxes(:filter, :city_ids, City.all, :id, :title) %><br>
            <label>Category:</label>
            <%#= collection_check_boxes(:filter, :category_ids, Category.all, :id, :title) %><br>-->

            <% City.all.each do |city| %>

              <%= check_box_tag 'by_city[]', city.id %>
              <%= h city.title %>

            <% end %>
            <br>
            <% Category.all.each do |category| %>

              <%= check_box_tag 'by_category[]', category.id %>
              <%= h category.title %>

            <% end %>
            <br>
            <label>Name:</label>
            <%= text_field_tag :by_title %><br>
            <label>Start Booking:</label>
            <%= datetime_select :filter, :start_booking %><br>
            <label>End Booking:</label>
            <%= datetime_select :filter, :end_booking %><br>
            <div><%= submit_tag 'Save' %></div>

          <% end %>
        </div>


        <div class='modal-footer'>
          <button type='button' class='btn btn-default' data-dismiss='modal'>Close</button>
        </div>
      </div>

    </div>
  </div>
</div>
<% @items.includes(:category).each do |item| %>
  <div class='container'>
    <h2><%= item.category.title %></h2>
    <div class='row'>
      <div class='col-md-6'>

        <ul class='list-group'>
          <li class='list-group-item'>Name:<%= item.name %></li>
          <li class='list-group-item'>Description:<%= item.description %></li>
          <li class='list-group-item'>Price:<%= item.price %></li>
        </ul>
      </div>
      <% if user_signed_in? %>
        <div class='col-md-2'>
          <%= link_to 'Do Booking', new_item_book_path(item), class: 'btn btn-primary' %>
          <%= link_to 'Do Review(not work)', item_reviews_path(item), class: 'btn btn-primary' %>
          <%= link_to 'Do Review for user(not work)', user_reviews_path(item.user_id), class: 'btn btn-primary' %>
        </div>


      <% end %>
    </div>
  </div>
<% end %>

app/views/items/me.html.erb
<div class="row">
  <div class="col-md-5"></div>
  <div class="col-md-1">
    <%= link_to new_item_path do %>
      <button class="btn btn-green btn-fab"><i class="fa fa-plus"></i></button>
    <% end %>
  </div>
  <div class="col-md-5"></div>
</div>



<% @items.includes(:category).each do |item| %>
  <div class='container' >
    <div class='row navbar-inverse'>
      <h2><%= item.category.title %></h2>
      <div class='col-md-1'>
        <div class='row'>
          <div class='col-md-6'>
            <%= link_to 'Delete', item_path(item), method: :delete, class: 'btn btn-red btn-raised' %>
          </div>
        </div>
        <div class='row'>
          <div class='col-md-6'>
            <%= link_to 'Update', edit_item_path(item), method: :get, class: 'btn btn-blue btn-raised' %>
          </div>
        </div>
      </div>
      <div class='col-md-6'>
        <ul class='list-group'>
          <li class='list-group-item'>Price:<%= item.name %></li>
          <li class='list-group-item'>Price:<%= item.price %></li>
          <li class='list-group-item'>Description:<%= item.description %></li>
        </ul>
      </div>
      <div class='col-md-1'>
        <div class='row'>
          <div class='col-md-1'>
          </div>
          <div class='col-md-2'>
            <button  style='margin-top:15px'>
              <%= link_to 'Show bookings for this item', item_books_path(item), method: :get, class: 'btn btn-green btn-raised' %>
            </button>
          </div>
          <div class='col-md-1'>
          </div>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/items/new.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-4'>
    </div>
    <div class='col-md-4 align-self-center'>
      <% if @item.errors.any? %>
        <div class='error_explanation'>
          <h4><%= pluralize(@item.errors.count, 'error') %></h4>
          <ul>
            <% @item.errors.full_messages.each do |msg| %>
              <li><%= msg %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_for @item do |f| %>
        <div class='form-group'>
          <label for='usr'>Description:</label>
          <%= f.text_area :description %><br>
          <label for='usr'>Price:</label>
          <%= f.text_field :price %><br>
          <div class='field'>
            <%= f.label :Select_item_Category %>
            <%= f.collection_select(:category_id, @categories, :id, :title, prompt: true) %>
            <%= f.label :image %><br>
            <%= f.file_field :image %>
          </div>
        </div>
        <%= f.submit 'Save' %>
      <% end %>
    </div>
    <div class='col-md-4'>
    </div>
  </div>
</div>

app/views/items/show.html.erb
<% @item.books.each do |book| %>
  <div class='container'>
    <h2><%= @item.category.title %></h2>
    <div class='row'>
      <div class='col-md-6'>
        <ul class='list-group'>
          <li class='list-group-item'>Price:<%= book.start_booking %></li>
          <li class='list-group-item'>Description:<%= book.end_booking %></li>
          <li class='list-group-item'>Price:<%= book.total_price %></li>
        </ul>
      </div>
    </div>
  </div>
<% end %>