config/routes.rb
Rails.application.routes.draw do
  get '/items/me', to: 'items#me'
  resources :items do
    resources :books
    resources :reviews
  end
  devise_for :users
  resources :users do
    resources :reviews
  end
  root to: 'items#index'
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Booking</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/font-awesome/4.3.0/css/font-awesome.min.css">

  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

  <style>
    body, html {
      height: 100%;
      margin: 0;
    }


  </style>

</head>
<body>
<div>
  <div>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <div class="navbar-brand"><%= link_to "Home", root_path %></div>
        </div>
        <div class="collapse navbar-collapse" id="myNavbar">
          <ul class="nav navbar-nav">
            <li><%= link_to 'Show Booking', root_path %></li>
            <% if user_signed_in? %>
              <li><%= link_to 'Add your item', new_item_path %></li>
              <li><%= link_to 'All your item', items_me_path %></li>
            <% end %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <% if user_signed_in? %>
              <div type="button" class="btn" style="margin-top: 7px">
                <li>
                  <%= link_to destroy_user_session_path, method: :delete do %>
                    <span class="glyphicon glyphicon-user"></span> Sign out
                  <% end %>
                </li>
              </div>
            <% else %>
              <div type="button" class="btn" style="margin-top: 7px">
                <li>
                  <%= link_to new_user_registration_path do %>
                    <span class="glyphicon glyphicon-user"></span> Sign Up
                  <% end %>
                </li>
              </div>
              <div type="button" class="btn" style="margin-top: 7px">
                <li>
                  <%= link_to new_user_session_path do %>
                    <span class="glyphicon glyphicon-log-in"></span> Login
                  <% end %>
                </li>
              </div>
            <% end %>
          </ul>
        </div>
      </div>
    </nav>
    <% if notice %>
      <div class="row">
        <div class="col-md-10">
        </div>
        <div class="col-md-2">
          <p class="alert alert-success"><%= notice %></p>
        </div>
      </div>
    <% end %>
    <% if alert %>
      <p class="alert alert-warning"><%= alert %></p>
    <% end %>
        <%= yield %>
  </div>
</div>
</body>
</html>